name: 🚀 SDK Feature Request
description: Ideas for new features and improvements in SDK
labels: enhancement in SDK
title: "[Feature in SDK]: "
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the new feature
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: Example
      description: |
        A simple example of the new feature in action (include Python code, YAML config, etc.)
        If the new feature changes an existing feature, include a simple before/after comparison.