name: 🚢 Ship new SDK release
description: Tasks for shipping new SDK release
labels: enhancement in SDK
title: "[Shipping new SDK release]: "
body:
  - type: markdown
    attributes:
      value: |
       - write release notes documentation in the changelog.MD
       - update version in all code examples in main README.md
       - update the version in headers in the file `/b24pysdk/_version.py`
       - update version in examples folder
       - checkout each example with release branch and test it
       - rebuild the list of the supported methods in SDK documentation
       - local pass linter
       - local pass PyTest tests
       - pass all integration tests by scope
  - type: input
    id: new-version
    attributes:
      label: new version
      placeholder: x.y.z
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of new release
    validations:
      required: false